sudo: required
language: ruby
install: bundle install --jobs=3 --retry=3
cache:
  directories:
  - vendor/bundle
rvm:
  - 2.2.3
  - 2.1.7
  - 2.0.0-p647
services:
  - mysql
env:
  - DEBIAN_FRONTEND=noninteractive PERL_MM_USE_DEFAULT=1 PERL5LIB=$HOME/perl5/lib/perl5 PATH=$HOME/bin:$HOME/perl5/bin/:$PATH
before_install:
  - sudo apt-get --yes install libaio-dev libaio1
  - mkdir ~/bin
  - cd ~/bin
  - curl -O https://github.com/miyagawa/cpanminus/raw/master/cpanm
  - curl -L https://cpanmin.us/ -o cpanm
  - chmod +x cpanm
  - cd -
  - cpanm MySQL::Sandbox
  - wget http://ftp.kaist.ac.kr/mysql/Downloads/MySQL-5.6/mysql-5.6.26-linux-glibc2.5-x86_64.tar.gz
  - make_replication_sandbox mysql-5.6.26-linux-glibc2.5-x86_64.tar.gz
  - gem install bundler -v 1.10.6
script:
  - bundle exec rake spec
